server:
  port: 8762

# https://piotrminkowski.wordpress.com/2017/02/05/part-1-creating-microservice-using-spring-cloud-eureka-and-zuul/
zuul:
  ribbon-isolation-strategy: semaphore
  prefix: /api
  routes:
    admin:
      path: /admin/**
      serviceId: ADMIN-SERVICE
    calculation:
      path: /calculation/**
      serviceId: CALCULATION-SERVICE

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000